### ISSUE TITLE
address decoder bit width needs to be calculated depending on the number of slaves

### ISSUE THREAD

**Issue by kristianharder** [ipbus/ipbus-software#121]
The address decoder template currently contains a hardcoded address width of 5 for the slave selection.  This does not work for more than 32 slaves. The address width should instead be determined dynamically, depending on the actual number of slaves referred to in the decoder logic.

**Comment by tswilliams** [comment]
Closing, since fix included in IPbus SW v2.6.2 (start of August), and no related problems reported since then.
