### ISSUE TITLE
static repo download location

### ISSUE THREAD

**Issue by dcsouthwick** [ipbus/ipbus-software#131]
Please consider providing a static location to download the repo definition files. This makes including the .repo files in scripts possible, wheras it otherwise requires manual intervention to install on a set of machines.

Formerly, your files were hosted at 

`http://ipbus.web.cern.ch/ipbus/doc/user/html/_downloads/ipbus-sw.centos${slc_version}.${arch}.repo`

Now it seems to resolve to something not understandable nor repeatable 

(I got `https://ipbus.web.cern.ch/ipbus/doc/user/html/_downloads/776a9345c99adc917987fc5cdb0aca9c/ipbus-sw.centos7.x86_64.repo`)

**Comment by tswilliams** [comment]
Hi,

Good point! I've updated the website so that the repo files are now accessible through simple URLs again - specifically:
```
http://ipbus.web.cern.ch/ipbus/doc/user/html/_downloads/ipbus-sw.centos${slc_version}.${arch}.repo
```

Cheers,
Tom
