### ISSUE TITLE
API for read/write without dispatch method call.

### ISSUE THREAD

**Issue by m-kru** [ipbus/ipbus-software#178]
Does `uhal` provide any API to read/write nodes without the need to call `dispatch()` method? I know, that I can group transactions and then call `dispatch()` only once, but in most cases I need to call `dispatch()` after single read/write. Right now I use following custom wrapper
```python
class ipbus(object):
    """
    Wrapper for objects used for IPbus communication
    """

    def __init__(self, hw, node):
        self.hw = hw
        self.node = hw.getNode(node)

    def write(self, val):
        self.node.write(val)
        self.hw.dispatch()

    def read(self):
        v = self.node.read()
        self.hw.dispatch()
        return v

    def readBlock(self, nwords):
        v = self.node.readBlock(nwords)
        self.hw.dispatch()
        return v
```
but maybe there is `uhal` way for this, that I don't know about?

**Comment by tswilliams** [comment]
Hi,

No, all calls of the read and write functions must be followed by calling the `dispatch()` method before the result of the read/write is accessed. The motivation behind this is when the reads and writes are encoded into IPbus packets, grouping multiple reads and writes into the same packet (where possible) greatly improves performance.

If calling the `dispatch()` method is inconvenient and/or cumbersome for a particular application, then the only solution is to write a custom wrapper classes or functions like the one that you posted above.

Cheers,
Tom
