### ISSUE TITLE
IPBus web site is unreachable

### ISSUE THREAD

**Issue by jhegeman** [ipbus/ipbus-software#212]
It appears that https://ipbus.web.cern.ch/ is down. And since both the software and the documentation are hosted there, this is no good...

**Comment by alessandrothea** [comment]
Are you still having issues? It works for me now.

**Comment by jhegeman** [comment]
It works for me again too. It started working again a little while after I submitted this ticket.

**Comment by tswilliams** [comment]
Hi,

I was off work today, so only just saw this. Didn't make any changes today, so the most likely cause that I can think of is a temporary glitch in EOS (or the EOS-webserver connection). The website is working for me now, so I'll close this issue, but do reopen if you continue to see problems

Cheers,
Tom
