### ISSUE TITLE
Installation gone wrong

### ISSUE THREAD

**Issue by mab049** [ipbus/ipbus-software#218]
Hello,
  while executing the instructions @alessandrothea 

https://ipbus.web.cern.ch/doc/user/html/software/install/yum.html

the last command fails because the link

http://www.cern.ch/ipbus/sw/release/2.7/repos/centos7/x86_64/base/RPMS

is broken

Can you help please ?

thanks

**Comment by tswilliams** [comment]
Hi,

This seems to have happened as a result of a central migration of the CERN webEOS areas to new hosting infrastructure. I've now fixed the problem. Let me know if you still have any problems.

Sorry for the disruption. 

Cheers,
Tom
