### ISSUE TITLE
Unused parameters in uhal/log/log_inserters.type.hxx

### ISSUE THREAD

**Issue by strilov** [ipbus/ipbus-software#232]
Hi,

There appear to be some unused parameters in uhal/log/log_inserters.type.hxx resulting in the compiler warnings below. Is this something which you could help with?

/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products_dev/uhal/v2_6_4/include/uhal/log/log_inserters.type.hxx:45:70: warning: unused parameter ‘aType’ [-Wunused-parameter]
   std::ostream& operator<< ( std::ostream& aStr ,  const _Type< T >& aType )

/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products_dev/uhal/v2_6_4/include/uhal/log/log_inserters.type.hxx:66:30: warning: unused parameter ‘aT’ [-Wunused-parameter]
   _Type< T > Type ( const T& aT )

Regards,
Stoyan

**Comment by tswilliams** [comment]
Hi,

I've removed the name of that unused parameter. I've merged this changed into the `master` branch, so it will be included in the next release.

Cheers,
Tom

**Comment by strilov** [comment]
Hi Tom,

Thanks very much for looking into this. There we two unused parameters, one at line 45 (now fixed), and another at line 66. Could you take a look at the one on line 66?

Regards,
Stoyan

**Comment by tswilliams** [comment]
Hi Stoyan,

I've just merged a fix for this into the master branch (along with fixes some other compiler warnings).

Cheers,
Tom
