### ISSUE TITLE
Additional information in exceptions

### ISSUE THREAD

**Issue by dgastler** [ipbus/ipbus-software#248]
Would it be acceptable to include the address for the offending action in these kinds of exceptions?
https://github.com/ipbus/ipbus-software/blob/ebf4cc3bd8b28f940ad35087216e5748c34ebba3/uhal/uhal/src/common/ClientInterface.cpp#L432
The function does include the uint32_t address, so it is in scope and would help in debugging if we could see the address in these kinds of exceptions.

**Comment by tswilliams** [comment]
Yes, completely agree on adding the address here.

**Comment by tswilliams** [comment]
PR opened; automatic builds & tests running ...
