### ISSUE TITLE
gcc 13 fails to compile

### ISSUE THREAD

**Issue by rhauser** [ipbus/ipbus-software#294]
We (ATLAS + LCG) are doing first tests with gcc 13 (and c++20). ipbus v2.8.9 fails to compile due to the use uintX_t types in pybind11/attr.h. The required <cstdint> header is nowhere included except in the numpy.h file

A full log can be found in the attached errors.txt file. I updated the pybind11 version locally to 2.10.4 (the latest) and that seems to fix the problem.

[error.txt](https://github.com/ipbus/ipbus-software/files/11663500/error.txt)

**Comment by tswilliams** [comment]
Hi

I've updated the pybind submodule to v2.10.4 in pull request #295 - it was in fact also required to support Python 3.11 on Alma9. This change is now included in the v2.8.10 tag of this repo.

Cheers,
Tom
