### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by PhyM73** [ipbus/ipbus-software#298]
The link "https://eu.edge.kernel.org/fedora/releases/34/Everything/x86_64/os/Packages/f/fedora-gpg-keys-34-1.noarch.rpm"
in the step 2 for RedHat/Alma/Rocky 9 on this [page](https://ipbus.web.cern.ch/doc/user/html/software/install/yum.html) doesn't work.

**Comment by tswilliams** [comment]
Hi,

I've now updated that download link, so that it should work now (make sure to reload the page to get the new link).

Cheers,
Tom
