### ISSUE TITLE
emp-butler git-clone link broken

### ISSUE THREAD

**Issue by abunickabhi** [ipbus/ipbus-software#299]
The second step of the page emp software guide [https://serenity.web.cern.ch/serenity/emp-fwk/software/install.html](url)

points to the url [](sudo curl https://serenity.web.cern.ch/serenity/emp-fwk/_downloads/emp.repo).

We are unable to fetch this URL as it is broken, can you look into it and fix the link?

**Comment by tswilliams** [comment]
I just checked that YUM repo download link and it's working fine. If you need to clone the `emp-toolbox` repo instead, you should use the instructions further down that page - https://serenity.web.cern.ch/serenity/emp-fwk/software/install.html#compiling-from-source

BTW, this repository is for the IPbus software - if you need to open tickets for the EMP software in the future, please use the following link instead: https://gitlab.cern.ch/p2-xware/software/emp-toolbox/-/issues
