### ISSUE TITLE
Packaging/installation issues on recent setuptools releases

### ISSUE THREAD

**Issue by thasti** [ipbus/ipbus-software#300]
We're deploying installations of ipbus-software on machines running OSes/python environments more recent than what Centos7/8 ship. One particular issue that keeps popping up is the installation of the uhal python bindings.

I'm building/installing using:

```
 make Set=uhal BUILD_UHAL_GUI=0 -j8
 make install prefix=$VIRTUAL_ENV Set=uhal
````

When using Python setuptools versions newer than at least release 44 (from 2020), the `make install` step fails with:

```
mkdir -p /home/xxx/ipbus/ipbus-software/uhal/python/rpm/RPMBUILD
cp /home/xxx/ipbus/ipbus-software/uhal/config//setupTemplate.py /home/xxx/ipbus/ipbus-software/uhal/python/rpm/RPMBUILD/cactuscore-uhal-python311.py
sed -i -e 's#__python_packages__#["uhal"]#' \
       -e 's#__packagename__#cactuscore-uhal-python311#' \
       -e 's#__version__#2.8.10#' \
       -e 's#__author__#Tom Williams#' \
       -e 's#__description__#Python bindings for the uHAL library#' \
       -e 's#__url__#https://ipbus.web.cern.ch/ipbus#' \
       -e 's#__project__#uhal#' \
       -e 's#__install_dir__#/opt/cactus#' \
       -e 's#__package_build_dir__#/home/xxx/ipbus/ipbus-software/uhal/python/rpm/RPMBUILD#' \
       /home/xxx/ipbus/ipbus-software/uhal/python/rpm/RPMBUILD/cactuscore-uhal-python311.py
# Change directory into pkg and copy everything into rpm/pkg
cd pkg && \
  find . -name "*" -exec install -D \{\} /home/xxx/ipbus/ipbus-software/uhal/python/rpm/RPMBUILD/\{\} \;
install: omitting directory '.'
install: omitting directory './uhal'
# Add a manifest file
echo "include */*.so" > /home/xxx/ipbus/ipbus-software/uhal/python/rpm/RPMBUILD/MANIFEST.in
# Change into rpm/pkg to finally run the customized setup.py
if [ -f setup.cfg ]; then cp setup.cfg /home/xxx/ipbus/ipbus-software/uhal/python/rpm/RPMBUILD/ ; fi
cd /home/xxx/ipbus/ipbus-software/uhal/python/rpm/RPMBUILD && \
  bindir=/home/xxx/ipbus/venv//bin python cactuscore-uhal-python311.py install --prefix=/home/xxx/ipbus/venv/ --exec-prefix=/home/xxx/ipbus/venv/
running install
/home/xxx/ipbus/venv/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/xxx/ipbus/venv/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
error: error in 'egg_base' option: '' does not exist or is not a directory
make[2]: *** [/home/xxx/ipbus/ipbus-software/uhal/config/mfPythonRPMRules.mk:97: install] Error 1
```

This issue seems to be coming from [setupTemplate.py](https://github.com/ipbus/ipbus-software/blob/master/uhal/config/setupTemplate.py#L42), where `package_dir = {'' : ''},` is specified. This is apparently considered "invalid logic" by setuptools ([see here](https://github.com/pypa/setuptools/issues/1935#issuecomment-566884315)). I can fix this issue by changing this line to `package_dir = {'' : '.'},` to properly refer to the root directory.

This change fixes the `bdist_egg` step, however the package is considered ['zip safe'](https://setuptools.pypa.io/en/latest/deprecated/zip_safe.html) by default and will then be deployed as a .egg archive - not noticing that it packages a `.so` file loaded at runtime (resulting in an ImportError when used). This again can be fixed by adding `zip_safe=False,` to the `setup()` call in `setupTemplate.py`.

Using these two fixes the build and import works fine on recent tool versions (Python 3.11, Setuptools 65.5.0). Would you consider taking up these fixes upstream? I can submit a PR if you want.

On a more general note, the packaging process also emits a number of warnings about the deprecation of invoking setup.py directly (in favor of pip) and the use of eggs vs wheels - but I guess that kind of change would imply a more significant rework of the packaging.

**Comment by tswilliams** [comment]
@thasti Thanks for implementing a fix.

Fixed in #301
